New upstream version 1.3.8

diff --git a/scripts/bootlist b/scripts/bootlist
--- a/scripts/bootlist
+++ b/scripts/bootlist
@@ -173,7 +173,7 @@ get_logical_device_name()
     if [[ $? -ne 0 ]]; then
 	echo ""
     else
-	echo $logical_name
+	echo $logical_name | tr -d '\000'
     fi
 }
 
@@ -207,11 +207,11 @@ show_bootlist()
     local devlist=$1
     local i
 
-    for i in `$NVRAM --print-config=${devlist} | sed 's/ /\n/g'`; do
+    for i in `$NVRAM --print-config=${devlist} 2> /dev/null | sed 's/ /\n/g'`; do
 	if [[ $TRANSLATE_NAMES = "yes" ]]; then
 	    name=`get_logical_device_name $i`
 	    if [[ -z $name ]]; then
-	        echo "Could not translate $i to logical device name"
+	        echo "Could not translate $i to logical device name" >&2
 	    else
 		case $name in
 		    eth*)   parse_eth_info $name $i ;;
@@ -230,7 +230,7 @@ show_bootlist()
 
 . $PSERIES_PLATFORM
 if [[ $platform != $PLATFORM_PSERIES_LPAR ]]; then
-    echo "bootlist: is not supported on the $platform_name platform"
+    echo "bootlist: is not supported on the $platform_name platform" >&2
     exit 1
 fi
 
@@ -459,6 +459,7 @@ if [[ ${#LOGICAL_NAMES[*]} -ne 0 ]]; then
 
         if [[ -z ${OF_DEVPATH[$ctr]} ]]; then
 	    echo "Device ${LOGICAL_NAMES[$ctr]} does not appear to be valid." >&2
+            exit 1
 	else
 	    # See if this is an ethernet adapter.  If so, the next entries
 	    # may be parameters for the bootlist entry.
